version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install sphinx>=5.0.0 myst-parser>=0.18.0
      - pip install -e .

sphinx:
  configuration: docs/conf.py
